---
- name: Upgrade pip2
  become: true
  ansible.builtin.command:
    cmd: pip install --upgrade pip

- name: Upgrade pip3
  become: true
  ansible.builtin.command:
    cmd: pip3 install --upgrade pip

- name: Make pip2 default pip executable
  become: true
  become_method: sudo
  ansible.builtin.file:
    src: /usr/local/bin/pip2
    dest: /usr/local/bin/pip
    owner: root
    group: root
    state: link
    force: yes

- name: Install pyvmomi package
  pip:
    name: pyvmomi
    state: latest
    executable: pip2

- name: Install pydeep package
  become: true
  become_method: sudo
  pip:
    name: pydeep
    state: latest
    executable: pip2

- name: Install m2crypto package
  become: true
  become_method: sudo
  pip:
    name: m2crypto
    state: latest
    executable: pip2

- name: Install mitmproxy package
  become: true
  become_method: sudo
  ansible.builtin.command:
    cmd: pip3 install -U mitmproxy

- name: Install pillow package
  become: true
  become_method: sudo
  pip:
    name: pillow
    state: latest
    executable: pip2

- name: Install pytesseract package
  become: true
  become_method: sudo
  pip:
    name: pytesseract
    state: latest
    executable: pip2

- name: Install protobuf package
  become: true
  become_method: sudo
  pip:
    name: protobuf
    state: latest
    executable: pip2

- name: Install sflock package
  become: true
  become_method: sudo
  pip:
    name: sflock
    state: latest
    executable: pip2

- name: Install distorm3 package
  become: true
  become_method: sudo
  pip:
    name: distorm3
    state: latest
    executable: pip2

- name: Install pycrypto package
  become: true
  become_method: sudo
  pip:
    name: pycrypto
    state: latest
    executable: pip2

- name: Install openpyxl package
  become: true
  become_method: sudo
  pip:
    name: openpyxl
    state: latest
    executable: pip2

- name: Install ujson package
  become: true
  become_method: sudo
  pip:
    name: ujson
    state: latest
    executable: pip2

- name: Install yara-python package
  become: true
  become_method: sudo
  pip:
    name: yara-python
    state: latest
    executable: pip2

- name: Install pyOpenSSL
  become: true
  become_method: sudo
  pip:
    name: pyOpenSSL
    state: latest
    executable: pip2

- name: Install setuptools
  become: true
  become_method: sudo
  pip:
    name: setuptools
    state: latest
    executable: pip2

- name: Install psycopg2
  pip:
    name: psycopg2
    state: latest
    executable: pip2

- name: Install psycopg2 in python3
  pip:
    name: psycopg2
    state: latest
    executable: pip3
