---

- name: Install python2
  become: yes
  become_method: sudo
  apt:
    name: python-minimal
    state: latest

- name: Install python-pip
  become: yes
  become_method: sudo
  apt:
    name: python-pip
    state: latest
