---
- name: Start Cuckoo Rooter
  become: true
  become_method: sudo
  shell: "{{ cuckoo_dir }}/bin/cuckoo rooter -g {{ cuckoo_user }} &"

- name: Wait for Rooter
  pause:
    minutes: 1

- name: Start Cuckoo Django Web Interface
  become: true
  become_method: sudo
  become_user: "{{ cuckoo_user }}"
  shell: "nohup {{ cuckoo_dir }}/bin/cuckoo web runserver 0.0.0.0:8000 >/dev/null 2>&1 &"

- name: Wait for Cuckoo Web
  pause:
    minutes: 1

- name: Start Cuckoo API
  become: true
  become_method: sudo
  become_user: "{{ cuckoo_user }}"
  shell: "nohup {{ cuckoo_dir }}/bin/cuckoo api --host 0.0.0.0 --port 8001 >/dev/null 2>&1 &"

- name: Wait for Cuckoo API
  pause:
    minutes: 1

- name: Start Cuckoo Sandbox
  become: true
  become_method: sudo
  become_user: "{{ cuckoo_user }}"
  shell: "nohup {{ cuckoo_dir }}/bin/cuckoo -d >/dev/null 2>&1 &"
